spring:
  application:
    name: laba3
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: postgres
    url: jdbc:postgresql://localhost:5434/postgres
  config:
    import: file:.env[.properties]
  security:
    jwt:
      secret: ${JWT_SECRET}